services:
  website:
    profiles: [production]
    container_name: timedial-website
    build: sidecars/website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - timedial-stats:/opt/timedial/html/stats:ro
  simhbuilder:
    container_name: timedial-simhbuilder
    build: sidecars/simh-builder
    environment:
      COMMIT: "f3c61c315a83ace8f2676bdc878962bf4528b5a6"
    volumes:
      - simh-bin:/opt/simh/bin
      - simh-src:/opt/simh/src
  webssh:
    container_name: timedial-webssh
    profiles: [production]
    image: python:3.12
    command: sh -c "pip install git+https://github.com/number42net/timedial-webssh.git && /usr/local/bin/wssh --port=8000" 
  backup:
    container_name: timedial-backup
    profiles: [production]
    build: sidecars/backup
    volumes:
      - type: bind
        source: keys/private-keys/sidecars-backup.key
        target: /root/.ssh/sidecars-backup.key
        read_only: true
      - timedial-home:/home:ro
  imap:
    container_name: timedial-imap
    build: sidecars/imap
    ports:
      - "143:143" # IMAP
      - "993:993" # IMAP SSL
    volumes:  
      - timedial-data:/data:ro
      - timedial-home:/home
      - certbot-etc:/etc/letsencrypt:ro
  slowproxy:
    container_name: timedial-slowproxy
    build: sidecars/slowproxy
    ports:
      - "1223:1223"   # Telnet
      - "2423:2423"   # Telnet
      - "9623:9623"   # Telnet
  timedial:
    build: .
    container_name: timedial-timedial
    hostname: timedial.org
    environment:
      DATA_DIR: /data
    ports:
      - "22:22"   # SSH
      - "23:23"   # Telnet
      - "24:24"   # Raw socket
    restart: unless-stopped
    volumes:
      - type: bind
        source: logs/archive
        target: /var/log/archive
      - type: bind
        source: logs/wtmp
        target: /var/log/wtmp
      - type: bind
        source: keys/host-keys
        target: /mnt/ssh_host_keys
        read_only: true
      - timedial-data:/data
      - timedial-home:/home
      - timedial-stats:/data/stats
      - simh-bin:/opt/simh-bin:ro
volumes:
  timedial-data:
  timedial-home:
  timedial-stats:
  certbot-etc:
  simh-bin:
  simh-src:
