version: '3.8'

services:
  timedial:
    build: .
    container_name: timedial
    hostname: timedial
    ports:
      - "22:22"   # SSH
      - "23:23"   # Telnet
      - "24:24"   # Raw socket
    restart: unless-stopped
    volumes:
      - type: bind
        source: data
        target: /sync
        read_only: true
      - timedial-data:/data
      - timedial-home:/home
volumes:
  timedial-data:
  timedial-home:
