version: '3.8'

services:
  timedial:
    build: .
    container_name: timedial
    ports:
      - "22:22"   # SSH
      - "23:23"   # Telnet
    restart: unless-stopped
    volumes:
      # - type: bind
      #   source: data
      #   target: /init
        # read_only: true
      - timedial-data:/data
volumes:
  timedial-data:
