services:
  website:
    container_name: timedial-website
    build: sidecars/website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - certbot
  certbot:
    container_name: timedial-certbot
    profiles: ["production"]
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: sh -c "certbot certonly --non-interactive --webroot -w /var/lib/letsencrypt --email toor@timedia.org --agree-tos --no-eff-email -d timedial.org && cp -L /etc/letsencrypt/live/timedial.org/fullchain.pem /etc/letsencrypt/live/timedial.org/privkey.pem"
  timedial:
    build: .
    container_name: timedial
    hostname: timedial.org
    environment:
      DATA_DIR: /data
    ports:
      - "22:22"   # SSH
      - "23:23"   # Telnet
      - "24:24"   # Raw socket
    restart: unless-stopped
    volumes:
      - type: bind
        source: logs/archive
        target: /var/log/archive
      - type: bind
        source: logs/wtmp
        target: /var/log/wtmp
      - type: bind
        source: ssh_host_keys
        target: /mnt/ssh_host_keys
        read_only: true
      - timedial-data:/data
      - timedial-home:/home
      - timedial-mail:/var/mail
volumes:
  timedial-data:
  timedial-home:
  timedial-mail:
  certbot-var:
  certbot-etc:
  