services:
  timedial:
    build: .
    container_name: timedial
    hostname: timedial.org
    environment:
      DATA_DIR: /data
    ports:
      - "22:22"   # SSH
      - "23:23"   # Telnet
      - "24:24"   # Raw socket
    restart: unless-stopped
    volumes:
      - type: bind
        source: logs/archive
        target: /var/log/archive
      - type: bind
        source: logs/wtmp
        target: /var/log/wtmp
      - type: bind
        source: ssh_host_keys
        target: /mnt/ssh_host_keys
        read_only: true
      - timedial-data:/data
      - timedial-home:/home
      - timedial-mail:/var/mail
volumes:
  timedial-data:
  timedial-home:
  timedial-mail:
