version: '3.8'

services:
  timedial:
    build: .
    container_name: timedial
    hostname: timedial
    environment:
      SYNC_DIR: /mnt/sync
      DATA_DIR: /data

    ports:
      - "22:22"   # SSH
      - "23:23"   # Telnet
      - "24:24"   # Raw socket
    restart: unless-stopped
    volumes:
      - type: bind
        source: data
        target: /mnt/sync
        read_only: false
      - timedial-data:/data
      - timedial-home:/home
volumes:
  timedial-data:
  timedial-home:
