version: '3.8'

services:
  timedial:
    build: .
    container_name: timedial
    ports:
      - "2222:22"   # SSH
      - "2322:23"   # Telnet
      - "2424:24"   # Raw socket
    restart: unless-stopped
    volumes:
      - type: bind
        source: data
        target: /tmpdata
        # read_only: true
      - timedial-data:/data
volumes:
  timedial-data:
