[emulator] # Required
label = "VAX 8600 with OpenVMS 7.1"
command = "vax8600 vax8600.ini"

[description] # Optional
publisher = "DEC"
original_date = "1978"
version = "7.1"
version_date = "1997"
text = [
    "Digital Equipment Corporation's powerful 1984 VAX 8600, running OpenVMS 7.1!",
    "This 32-bit system features robust virtual memory support and an operating system unlike anything else",
]
login_information = ["Username: SYSTEM / Password: simpassword"]
